### ISSUE TITLE
Brawl Stars Token.

### ISSUE THREAD

**Issue by DIBSTERYT** [gregbubnis/brawl#1]
Hey, this isn't a issue with your code, but just a heads up. Brawl Stars tokens are encoded using HS512 algorithm, which can be reversed to get token information, including the IP designated to that token. I recommend you keep your token out of public repositories, in case they are testing tokens for your IP, or for a VPS IP.

Best Regards, DIBSTER. ✌️

**Comment by gregbubnis** [comment]
I really appreciate this! 

I just wiped the commit history that contained API tokens, so I think that should do the trick. I am curious, only if you feel like sharing, how you found this repo?

**Comment by DIBSTERYT** [comment]
Hey gregbubnis, I came across this this repository while checking out other open source projects centered around Brawl Stars. This one caught my eye, so I took a deeper look at this repository.

Also if you wish, you could completely delete the Brawl Stars token from the dashboard, and generate a new one, in case anyone did in fact manage to get the token. Most people don't know that the tokens can actually be decoded, so I was just wanting to make you aware of it, and hopefully prevent bad actors from using it.

Best Regards, DIBSTER. ✌️

**Comment by gregbubnis** [comment]
Yo I think we played vs each other in CL a few match days ago. You drafted tick before I could take him! Anyways you guys wrecked us so ggs :)

**Comment by DIBSTERYT** [comment]
Alright, I’ll close this issue now, have a good day.
